### ISSUE TITLE
不能破验证码？

### ISSUE THREAD

**Issue by zzstrwolf** [fcfangcc/Crawler#1]
QQ 66766616
希望交流

**Comment by fcfangcc** [comment]
我自己测试的时候一直没遇到要输入验证码，忘记了这个事情。

@zzstrwolf 现在支持手动输入验证码了。自动识别的话还做不到.
另一个方案是可以利用保存cookie到文件来实现第一次登录的时候需要输入验证码，但是我试了下没成功。
