### ISSUE TITLE
你好，我想问怎么发url链接哇？

### ISSUE THREAD

**Issue by xubigshu** [fcfangcc/Crawler#2]
非常感谢你的代码，我用tiezi类发一个url，显示出去是文本的形式。我想问问如何发一个链接的形式哇？

**Comment by fcfangcc** [comment]
@xubigshu 如果你是在回复中插入url的话,你可以这样写：

tiezi.reply("百度:[url]http://tieba.baidu.com[/url]")

url地址用标签[url][/url]包起来.

另外百度可能会对部分他不信赖的url删贴.....

**Comment by xubigshu** [comment]
哦哦 谢谢哈
